### ISSUE TITLE
Computed property that contains other computed property doesn't bind

### ISSUE THREAD

**Issue by arshaw** [fullcalendar/fullcalendar-vue#119]
Originally reported by @lllopo in #96:

> ...When the options object is set in any other way, but a computed property and contains other computed properties as values, it doesn't bind properly. I'm not talking for the 'undefined' errors when this is done in the data() function - this is normal, but I'm talking for the case, when this is done on monted() for example. For some reason - in this case the computed properties bound options are not reactive.

https://codesandbox.io/s/fc5-cumputed-not-reactive-i2gqc?file=/src/DemoApp.vue

> ...This time it is absolutely the same as the one above, with the only difference, that the calendar options are part of the data function. As result, while kickitValue is well reactive and working (printed below the link), nothing happens on the FC side, so the option is not reactive.

**Comment by arshaw** [comment]
I think things are working as expected. Non-computed properties are being mixed with computed properties in such a way where they wouldn't all update.

```
calendarOptions (NOT computed)
  |
  | (depends on)
  v
  toolbarswitch (IS computed)
    |
    | (depends on)
    v
    kickitValue (NOT computed)
```

If the `kickitValue` changes, it WILL update the `toolbarswitch` value, but then the `toolbarswitch` value will NOT update the `calendarOptions` value because `calendarOptions` is not a computed property.

You'll need to make `calendarOptions` a computed property here to make this scenario work. As it stands right now, things are not wired up correctly to achieve what you want to achieve.

**Comment by arshaw** [comment]
Does that make sense?

**Comment by lllopo** [comment]
> Does that make sense?

@arshaw Well ... not really :-), but also - looks like it is not a shortcoming of FC, but Vue itself. I mean - as far as calendarOptions is a reactive property (and it definitely is), even without being a computed one, then as far as it is bound to a value that changes, it should follow ... BUT it doesn't when the thing in question is a computed property. Weird and not nice, but you're completely right it's not a FC issue. Still - I must admit I regard it is a shortcoming by design of the new approach with the one big options object, 'cause with the old approach - it won't even cross my mind to bind everything this way.

In all cases - I'm still glad we put this to discussion as it will serve to others as "don't do it this way" lesson :-).

**Comment by ihorbond** [comment]
So which way are we supposed to do it ? Success callback ? Ran into the same problem, it seems counterintuitive. And we already purchased the license. Should we just revert to v4 ? Will this behavior be updated in v6 again ?
