### ISSUE TITLE
Dynamically block a resource on eventAllow 

### ISSUE THREAD

**Issue by nfunwigabga** [fullcalendar/fullcalendar-vue#13]
I have a working `eventAllow` function as follows:
```javascript
eventAllow(dropLocation, draggedEvent){
   const room = dropLocation.resource.extendedProps
   const meeting = draggedEvent.extendedProps
   return meeting.total_participants <= room.seats
}
```

This works nicely and does now allow the user to drop a meeting in a room where there are not enough seats. However, I will like to change the CSS class dynamically for the room that does not meet the criteria and grey it out. Any idea how this can be done?

**Comment by nfunwigabga** [comment]
I was able to do this using a combination of `eventDragStart`, `eventDragEnd` and `EventAllow` by targeting the `data-resource-id` attribute of the row in the resource view and appending a new css class to it `bg-grey`. Dirty way I guess, but for now it solves my problem.

```javascript
eventDragStart(evt) {
          const meeting = evt.event.extendedProps
          this.calendarResources.forEach(r => {
            if(meeting.participants > r.seats ){
              $(`[data-resource-id="${r.id}"]`).addClass('bg-grey')
            }
          })
      },

  eventDragStop(evt) {
          $(`[data-resource-id]`).removeClass('bg-grey')
   },
```

then `eventAllow` same as above.

**Comment by acerix** [comment]
If this is a question, please refer to the [support page](https://fullcalendar.io/support/) and use [Stack Overflow](https://stackoverflow.com/questions/tagged/fullcalendar) for help.  If this is a bug, please supply a [runnable, stripped-down demonstration](http://fullcalendar.io/wiki/Reduced-Test-Cases/). Also, if your issue is not specific to the Vue component, please use the [main repo](https://github.com/fullcalendar/fullcalendar).
