### ISSUE TITLE
Resources not rendering on resource-timeline

### ISSUE THREAD

**Issue by nietoroger** [fullcalendar/fullcalendar-vue#162]
Resource timeline view is not rendering resources from an fetch request even if they are correct in format (id, label).

Example:
https://codesandbox.io/s/fullcalendar-bug-forked-1eylg?file=/src/DemoApp.vue

**Comment by acerix** [comment]
The issue is that "resources" is not defined when initialized, ie. when the `data` function returns. (eg. https://codesandbox.io/s/fullcalendar-bug-forked-uwwqk?file=/src/DemoApp.vue )  

To supply resources from a URL you can use supply them as JSON or "as a function". 

https://fullcalendar.io/docs/resources-function

**Comment by nietoroger** [comment]
Thanks a lot @acerix .. Great Job!!!
