### ISSUE TITLE
More than 1 full calendar on the same page.

### ISSUE THREAD

**Issue by V3ct0rek** [fullcalendar/fullcalendar-vue#176]
Hello,
I have got a problem with full calendar. I have to use more than 1 calendar on the same page, but when i try use it, one callendar is working, but the second one is not working(business hours and selectable are not working). Do you have any solution in vue 3 syntax? I have the solution in jquery but i want to have only vue syntax in file .

**Comment by acerix** [comment]
Please refer to the [support page](https://fullcalendar.io/support/) and use [Stack Overflow](https://stackoverflow.com/questions/tagged/fullcalendar) for help.  If this is a bug, please supply a [runnable, stripped-down demonstration](http://fullcalendar.io/wiki/Reduced-Test-Cases/).

**Comment by wartmanm** [comment]
I'm experiencing the same issue.  Here is a complete, minimal test case: https://codepen.io/wartmanm/pen/dydgEMm
The "Show weekends" checkbox at the top of the page updates the `weekends` option for both calendars.  However, only the right-hand one updates.

The underlying cause is that the component's `mounted()` callback assigns to `this.$options` [1].  However, in Vue 3, $options is shared across all instances of a component. [2]  Because of this, `getApi()` will always return the API of the most recently mounted calendar, and render to it, no matter which calendar you use.

I'd be happy to put together a pull request to change it to a per-instance property, if desired.

[1] https://github.com/fullcalendar/fullcalendar-vue/blob/d203b0c693b08a62cccdeb47a38fc609d41205ed/src/FullCalendar.ts#L30-L31
[2] https://github.com/vuejs/core/blob/bdffc1/packages/runtime-core/src/componentOptions.ts#L928-L933.  Note the comment above the function.
$options's getter calls `resolveMergedOptions` here: https://github.com/vuejs/core/blob/bdffc1/packages/runtime-core/src/componentPublicInstance.ts#L240
