### ISSUE TITLE
Named timezone is not getting set

### ISSUE THREAD

**Issue by Krantisinh** [fullcalendar/fullcalendar-vue#37]
## Problem

Full calendar with Vue does not take in to account named time zones. If we set the prop `timeZone` to any named timezone other than `local`, it by default sets to `UTC`.

For example -

`timeZone='local' // calendar will be rendered in local time successfully`
`timeZone='UTC' // calendar will be rendered in UTC time successfully`

`timeZone='Australia/Sydney' // will be defaulted to UTC time` 

## Expected Behaviour
When we specify a named timezone in `timeZone` prop, calendar should be rendered considering the value of the prop. For example -

 `timeZone='Australia/Sydney' // calendar should have been rendered considering the Sydney time instead of UTC time.`

## Reproduction link
https://codesandbox.io/embed/fullcalendar-vue-pj5v4

### Works with default JS implementation
Timezone works perfectly fine in vanila js implementation of full calendar -  https://codepen.io/pen/?&editable=true&editors=001, however fails with its vue implementation as explained above.

P.S. I'm using the named time zones from https://fullcalendar.io/demo-timezones.json list.

**Comment by acerix** [comment]
Thanks, confirmed.

**Comment by arshaw** [comment]
That's what's supposed to happen if you don't provide a named-timezone plugin
https://fullcalendar.io/docs/timeZone#with-a-timezone-plugin

If would like to see how your non-Vue example works, but the link is broken. Could you post one that works?

**Comment by Krantisinh** [comment]
@arshaw https://fullcalendar.io/docs/timeZone-demo
This one in the official docs works with plain JS implementation.

**Comment by douggrubba** [comment]
Did this ever get addressed?  If not does anybody have a cleanish work around.  I'm definitely butting up against this.  The calendar w/ business hours seems to be respecting the timezone, but the dateclick does not seem to be at all as described above.

**Comment by kamesh95** [comment]
@acerix @arshaw Is there any doc on how to use it with calendar options? Since, the named timezone was not working for me (defaulting to UTC as mentioned in the issue above), I tried using moment-timezone plugin but unfortunately it gives error. See attached error. Thanks

I am using full calendar v5 and moment-timezone plugin v5 with angular 9. I have created a json object of options and using it in html like
 `<full-calendar #calendar [options]="calendarOptions"></full-calendar>`

<img width="965" alt="Screenshot 2020-07-15 at 12 02 52 AM" src="https://user-images.githubusercontent.com/16370987/87463134-980cea80-c62e-11ea-9c9f-53b7c1c2ad6f.png">

**Comment by arshaw** [comment]
@Krantisinh, the reason you are seeing the event-rendering difference between vanilla JS and Vue has nothing to do with Vue. The reason is that the [demo hosted on fullcalendar.io](https://fullcalendar.io/docs/timeZone-demo) is requesting a URL like this:

https://fullcalendar.io/demo-events.json?start=2020-06-28T00%3A00%3A00Z&end=2020-08-09T00%3A00%3A00Z&timeZone=UTC

It sends the timeZone as a GET parameter. The script (which is a PHP script behind the scenes) looks at this param and sends back events with datetime values in the given timeZone.
