### ISSUE TITLE
Does refetch-events work for Google Calendat EventSources

### ISSUE THREAD

**Issue by good-marketing** [fullcalendar/fullcalendar-vue#58]
I have my fullcalendar set up using EventSources with different Google Calendars.  When I drag and drop and event I want to refetch the events from Google Calendar (including the Google Calendar properties). 

I use `this.$refs.calendar.$emit('refetch-events')` to refetch the events. From the Vue inspector I can see that the event is called, however the payload is empty. 

Does the refetch-events method also work with Google Calendar or should try another means of refetching and rendering the events?

Thanks!

**Comment by acerix** [comment]
refetchEvents also works for Google calendar, you can see the network requests in this demo:

https://codepen.io/acerix/pen/dyyLbYa

Please post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/) if it's not working. Would really appreciate it because the time saved reproducing will be time spent fixing.
