### ISSUE TITLE
@eventRender not firing on iOS devices and Safari

### ISSUE THREAD

**Issue by kwanwooi25** [fullcalendar/fullcalendar-vue#6]
Hi, thank you so much for providing the official vue wrapper for fullcalendar.

I have recently applied it to our product and faced an issue that the event items are not shown on specific browser and device like Chrome on iphone, Chrome on ipad and Safari on mac. As I dig in, I found that @eventRender function is not firing on Safari on mac.

Could you please look into this so I could resolve the issue? I am attaching the images and hope it might be helpful.
Thanks in advance.

Safari on mac: .fc-event-container is empty
<img width="643" alt="Screen Shot 2019-04-13 at 2 47 19 PM" src="https://user-images.githubusercontent.com/28733869/56075592-c1254680-5dff-11e9-979f-16a6fd73f7ef.png">

Chrome on mac
<img width="642" alt="Screen Shot 2019-04-13 at 2 48 21 PM" src="https://user-images.githubusercontent.com/28733869/56075591-c08cb000-5dff-11e9-9722-f86819a21a1d.png">

**Comment by arshaw** [comment]
@kwanwooi25 do you think your issue is related to this?
https://github.com/fullcalendar/fullcalendar/issues/4610

If not, would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

**Comment by kwanwooi25** [comment]
@arshaw It is. I tested with the datetime format of `YYYY-MM-DDTHH:mm:ss` and it works. Thank you so much! I will close the issue!
