### ISSUE TITLE
Date navigation 'prev' not working properly

### ISSUE THREAD

**Issue by janswist** [fullcalendar/fullcalendar-vue#99]
#### Reproduction link:
https://codesandbox.io/s/elated-hoover-cll1f

#### Expected:
to click on `prev` button multiple times and have date range properly rendered.

#### Actually happening:
after one click on `prev` button calendar goes one day back (which is ok), but following clicks seem not to change date even though `datesSet` event is firing off.

**Comment by acerix** [comment]
Thanks, confirmed.  The issue is not specific to Vue and was reported in the main repo:

https://codepen.io/acerix/pen/GRoxZdY?editors=001

https://github.com/fullcalendar/fullcalendar/issues/5319
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.

It works by setting `dateIncrement`:

https://codepen.io/acerix/pen/MWKVyGK?editors=001
